name: TheStashNyc
favicon: null
layout_spectrum: 0.4447220319416374
typography_spectrum: 0.48506304901093245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6554501170758158
  lightness: 0.013830505544319749
  saturation: 0.797172092134133
  rhythmicContrast: 0.5983758552465588
purpose: []
